"""learned playlist profiles

Revision ID: cacc1edadb16
Revises: 2aac9b59ce46
Create Date: 2026-08-06 10:40:21.620842
"""
from __future__ import annotations

from typing import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = 'cacc1edadb16'
down_revision: str | None = '2aac9b59ce46'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('playlist_artists',
    sa.Column('playlist_id', sa.Text(), nullable=False),
    sa.Column('artist_id', sa.Text(), nullable=False),
    sa.Column('tracks', sa.Integer(), nullable=False),
    sa.Column('learned_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('playlist_id', 'artist_id', name=op.f('pk_playlist_artists'))
    )
    with op.batch_alter_table('playlist_artists', schema=None) as batch_op:
        batch_op.create_index('ix_playlist_artists_artist_id', ['artist_id'], unique=False)

    op.create_table('playlist_genres',
    sa.Column('playlist_id', sa.Text(), nullable=False),
    sa.Column('genre', sa.Text(), nullable=False),
    sa.Column('tracks', sa.Integer(), nullable=False),
    sa.Column('learned_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('playlist_id', 'genre', name=op.f('pk_playlist_genres'))
    )
    with op.batch_alter_table('playlist_genres', schema=None) as batch_op:
        batch_op.create_index('ix_playlist_genres_genre', ['genre'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('playlist_genres', schema=None) as batch_op:
        batch_op.drop_index('ix_playlist_genres_genre')

    op.drop_table('playlist_genres')
    with op.batch_alter_table('playlist_artists', schema=None) as batch_op:
        batch_op.drop_index('ix_playlist_artists_artist_id')

    op.drop_table('playlist_artists')
    # ### end Alembic commands ###
