"""initial schema

Revision ID: e6e6895d6ff4
Revises: 
Create Date: 2026-08-05 19:09:39.732127
"""
from __future__ import annotations

from typing import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = 'e6e6895d6ff4'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('artists',
    sa.Column('artist_id', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('genres_json', sa.JSON(), nullable=False),
    sa.Column('fetched_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('artist_id', name=op.f('pk_artists'))
    )
    op.create_table('playlists',
    sa.Column('playlist_id', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('hotkey', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('playlist_id', name=op.f('pk_playlists')),
    sa.UniqueConstraint('hotkey', name=op.f('uq_playlists_hotkey'))
    )
    op.create_table('tracks',
    sa.Column('track_id', sa.Text(), nullable=False),
    sa.Column('artist_ids', sa.JSON(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('artist_name', sa.Text(), nullable=False),
    sa.Column('added_at', sa.DateTime(), nullable=False),
    sa.Column('genres_json', sa.JSON(), nullable=True),
    sa.Column('synced_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('track_id', name=op.f('pk_tracks'))
    )
    with op.batch_alter_table('tracks', schema=None) as batch_op:
        batch_op.create_index('ix_tracks_added_at', ['added_at'], unique=False)

    op.create_table('decisions',
    sa.Column('track_id', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'sorted', 'skipped', name='status', native_enum=False, length=16), nullable=False),
    sa.Column('playlist_id', sa.Text(), nullable=True),
    sa.Column('decided_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint("(status = 'sorted') = (playlist_id IS NOT NULL)", name=op.f('ck_decisions_sorted_has_playlist')),
    sa.CheckConstraint("status IN ('pending', 'sorted', 'skipped')", name=op.f('ck_decisions_status_values')),
    sa.ForeignKeyConstraint(['track_id'], ['tracks.track_id'], name=op.f('fk_decisions_track_id_tracks'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('track_id', name=op.f('pk_decisions'))
    )
    with op.batch_alter_table('decisions', schema=None) as batch_op:
        batch_op.create_index('ix_decisions_status', ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('decisions', schema=None) as batch_op:
        batch_op.drop_index('ix_decisions_status')

    op.drop_table('decisions')
    with op.batch_alter_table('tracks', schema=None) as batch_op:
        batch_op.drop_index('ix_tracks_added_at')

    op.drop_table('tracks')
    op.drop_table('playlists')
    op.drop_table('artists')
    # ### end Alembic commands ###
